name: taj_al_amal_erp
description: Custom ERP system for TAJ AL AMAL company, built with Flutter for multi-platform support.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  email_validator: ^2.1.17
  sqflite_common_ffi: ^2.3.0
  sqflite_common_ffi_web: ^0.4.3+1
  mongo_dart: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
