name: taj_al_amal_erp
description: Custom ERP system for TAJ AL AMAL company, built with Flutter for multi-platform support.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  email_validator: ^2.1.17
  mongo_dart: ^0.10.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  firebase_database: ^10.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
